/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package javagradle;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.DisplayName;

import org.junit.jupiter.api.Test;
import ultima.NestedCollection;

class NestedCollectionTest {
  @Test
  @DisplayName("Write assertions for value in sList")
  void appHasAGreeting() {
    NestedCollection classUnderTest = new NestedCollection();
    System.out.println("Test: " + classUnderTest.getTest());
    assertEquals("B", classUnderTest.getTest());
  }

}
