/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package blockchain;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.DisplayName;

import org.junit.jupiter.api.Test;
import blockchain.Wallet;

class WalletTest {
  @Test
  @DisplayName("chceck generated keys")
  void appHasAGreeting() {
    Wallet classUnderTest = new Wallet();
    System.out.println("Test: " + classUnderTest.get());
    assertEquals("B", classUnderTest.get());
  }

}
